# Generated by Django 4.2.13 on 2024-06-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='massar_id',
            new_name='massarID',
        ),
    ]
