# Generated by Django 4.2.13 on 2024-06-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_alter_user_massarid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='massarID',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
