# Generated by Django 4.2.13 on 2024-06-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_alter_user_massarid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classe',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
