# Generated by Django 4.2.13 on 2024-06-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0006_user_displayed_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='displayed_password',
            field=models.BinaryField(null=True),
        ),
    ]
